### ISSUE TITLE
Configured everything but nothing happens

### ISSUE THREAD

**Issue by Gotouille** [tsenay/Airzonecloud-HomeAssistant#1]
Hi,
I configured everything as explained:
Added the airzonecloud folder, added the configuration in configuration.yaml, rebooted

Nothing happens, nothing is added in the devices nor in the integrations.

Am I missing something?

**Comment by jfernandezgersol** [comment]
Hi @Gotouille, @tsenay 

I followed the README and in my case I can see the three cards of my 3 bedrooms but only one of them (the main one/master) shows controls to enable the different climate modes. The other two cards are showing only the current temperature. 

If I enable any mode then the card shows the changes but nothing happens on my airzone installation. If I login in Airzone Cloud I cannot see any changes neither.

Maybe I am missing something too.

**Comment by tsenay** [comment]
Hello, the HVAC mode is only available on primary device in the New airzone API. All secondary devices can't set/change the hvac mode. 

Workaround: change hvac mode on master device

Improvement: I need to check if I can set the hvac mode to primary device when operating secondaries

**Comment by tsenay** [comment]
@Gotouille 

Did you installed the integration with HACS? That's the better installation way

**Comment by Gotouille** [comment]
@tsenay  
No, I downloaded it and put it in the right folder, then I added
- platform: airzonecloud
username: myemail
password: mypasswd
Scan_interval: 30
With the right spacing

And after multiple reboots, still nothing happens.

After reading your answer, I installed it with HACS, then put the above configuration again, and after a reboot, still nothing. 

Is it supposed to add itself in the devices panel, or in the integration panel? Or is it supposed to appear in the integration search function?
I had max13fr integration working when his/her version was still working without an issue, so I am assuming I'm not making an obvious mistake in configuring yours. 

Do you have any other insight?

**Comment by Gotouille** [comment]
The only log I can find that talk about airzone is this one:

2021-12-13 20:28:01 WARNING (SyncWorker_0) [homeassistant. loader] We found a custom integration airzonecloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by tsenay** [comment]
@Gotouille,
Can you comment with relevant configuration values. This can help to troubleshoot

**Comment by tsenay** [comment]
Is your config is under climate section? 
Should be:

```yaml
climate:
  - platform: airzonecloud
    username: ...

```

**Comment by Gotouille** [comment]
Hello again.
I'm not sure what would be of use to you so I'm sending everything I can think of.
The config is indeed under the climate section :
![Screenshot_20211213-213610](https://user-images.githubusercontent.com/78366102/145885355-e8ea50b0-ec58-44cd-9126-e83cc669c993.png)

I installed the integration through HACS under the "integrations" type :
![Screenshot_20211213-213809](https://user-images.githubusercontent.com/78366102/145885558-d082b1cf-95d4-45ed-a650-6e41913422af.png)

HAss is installed on a raspberry pi and has the latest home assistant version of December

Sorry for the inconvenience and thank you for the help

**Comment by jfernandezgersol** [comment]
> 

Yes, you are right. I can set the hvac mode on master device but I cannot start any of the 3 devices. There is no button in the cards to turn them on. I send you a screenshot: 

![Screenshot_2021-12-13-21-45-24-56_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/15782871/145886149-e279271e-44e3-43d0-a2ae-660fc5a40b61.jpg)

I would expect to have a method turn_on in the class AirzonecloudSystem like there is one in the AirzonecloudZone which btw is not referenced anywhere.

I could turn on my devices using the Max Cloud API directly.

Maybe I am missunderstanding something. I am a newbie with the Airzone topics. :)

**Comment by mvillarejo** [comment]
same thing here @jfernandezgersol.

Good start @tsenay! thank you for sharing

**Comment by tsenay** [comment]
Fixed in release 0.1.2
